src/linters/gofmt.js, test/linters/linters.test.js, test/linters/params/gofmt.js, test/linters/params/prettier.js, test/utils.js
I noticed while working on a new linter that my test was passing even though the stdout/stderr was incorrect.
This seems to be fallout from this refactor:
https://github.com/samuelmeuli/lint-action/commit/73e9574651632c461b95746ebb53b6f117d99fb6
I had to update the timezone date regex to allow my timezone as well.
I also updated the `gofmt` linter, since it sends its output to stdout. I also fixed the tests for it.
I updated the prettier test to remove the fix assertion on stdout because, on my machine, it outputs something like:
```
Expected: ""
Received: ".prettierrc.json 26ms
file1.js 18ms
file2.css 45ms
package.json 6ms"
```
to stdout.
=> Fix linter stdout/stderr assertions

src/git.js
Switch to old commands for branch switching to allow for versions of git < 2.23.0
Edit: I'll admit to not getting to actually test this except for manually issuing the commands and seeing that git seems to behave the same way.
=> Replace `git switch` command for better compatibility

src/linters/black.js, src/linters/flake8.js
I wanted to use black and flake8 inside a virtual env so i needed to be able to use the prefix part, 
but go stuck with black installed verification.
here is an alternative for the check.
=> Use command prefix for Black/Flake8 install checks

action.yml
`Unexpected input 'github_token'` warning shown.
I think a cause is no `github_token` field in inputs list of action.yml.
ref https://github.com/samuelmeuli/lint-action/issues/53
=> Fix missing `github_token` input in `action.yml`

.github/workflows/test.yml, README.md, action.yml, src/linters/index.js, src/linters/php-codesniffer.js, test/linters/linters.test.js, test/linters/params/php-codesniffer.js, test/linters/projects/php-codesniffer/file1.php, test/linters/projects/php-codesniffer/file2.php, test/linters/projects/php-codesniffer/phpcs.xml.dist
Fixes #69
The following tasks have been done:
=> Add PHP_CodeSniffer support

.github/workflows/test.yml
Try to fix the build error in https://github.com/samuelmeuli/lint-action/pull/73/checks?check_run_id=926787280
```
🌱 Cloning SwiftFormat 0.43.5
🌱 Resolving package
🌱 Building package
🌱 Installed SwiftFormat 0.43.5
🌱 Linked swiftformat 0.43.5 to /usr/local/bin
🌱 Installed 1/1 package
🌱 Cloning SwiftLint 0.38.1
🌱 Resolving package
🌱 Building package
🌱 Installed SwiftLint 0.38.1
🌱  An executable that was not installed by mint already exists at /usr/local/bin/swiftlint that is symlinked to /usr/local/Cellar/swiftlint/0.39.2/bin/swiftlint.
Overwrite it with Mint's symlink? (y/n) 
##[error]Process completed with exit code 1.
```
Related: https://github.com/yonaskolb/Mint/issues/182
=> Unlink Hombrew's swiftlint to fix linking by mint

.github/workflows/test.yml
There's current a hidden error in the macos-latest runner.
```
sudo ln -sf /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/bin/ruby /usr/bin/ruby
ln: /usr/bin/ruby: Operation not permitted
(node:1502) UnhandledPromiseRejectionWarning: Error: The process 'sudo' failed with exit code 1
at ExecState._setResult (/Users/runner/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:547:25)
at ExecState.CheckComplete (/Users/runner/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:530:18)
at ChildProcess.<anonymous> (/Users/runner/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:430:27)
at ChildProcess.emit (events.js:210:5)
at maybeClose (internal/child_process.js:1021:16)
at Socket.<anonymous> …
```
=> Replace `actions/setup-ruby@v1` with `ruby/setup-ruby@v1` in test workflow

src/linters/flake8.js
Fixes #64. 
This adds the same code as already used in https://github.com/samuelmeuli/lint-action/blob/d99462ff1ed51fc7931b756e47392208d3988e04/src/linters/mypy.js#L84-L88.
=> Fix path replacement for Flake8

README.md, action.yml, src/index.js
Fixes #61.
Example with `check_name: "${linter} (${dir})"`
=> Add action input for custom check names

src/index.js
Currently the annotations are attached to the latest commit for commits to a branch.
In the example above the check belongs to the "Update token" commit.
=> Attach commit annotation to the correct commit for non-pull-requests

README.md, action.yml, dist/index.js, src/index.js
Fixes #60.
This adds a new input option `continue_on_error` to allow the main run to fail the workflow. For v1 the default will be `true` to keep the current behaviour.
=> Add continue_on_error input

.github/workflows/test.yml
This should fix the current macOS build errors.
```
🍺  /usr/local/Cellar/mint/0.16.0: 6 files, 3MB
Error: No such keg: /usr/local/Cellar/swiftlint
🌱 Linked swiftformat 0.43.5 to /usr/local/bin
🌱 1 package up to date
🌱  An executable that was not installed by mint already exists at /usr/local/bin/swiftlint.
Overwrite it with Mint's symlink? (y/n) 
Error: Process completed with exit code 1.
```
Related: https://github.com/yonaskolb/Mint/releases/tag/0.16.0
=> Use --overwrite option for mint to fix macOS tests

dist/index.js, src/utils/action.js
=> Increase maxBuffer from 1MB to 20MB to avoid truncated linting results

README.md, action.yml, src/git.js, src/index.js
Running into issues that if `eslint` and `prettier` both run on a file my npm pre-commit hook will fail. Suggesting this but also running 
If you'd like to close / logging for SEO that in the meantime I'm also just running this .yml between ci and lint-action: 
```
- name: Remove commit hooks
run: rm .git/hooks/pre-commit
run: rm .git/hooks/pre-push
```
=> add git_no_verify flag for potential hook issue

src/linters/mypy.js
Right now checking for `mypy` fails if you require a prefix (for example, `poetry run` in my case). This PR solves this problem.
=> Add prefix to mypy check

src/github/api.js, src/index.js
* Show full error message including documentation URL, see https://docs.github.com/en/rest/overview/resources-in-the-rest-api#client-errors
* Don't let the action fail if a check run could not be created
Supersedes #347.
=> Improve handling for failed check runs

README.md, src/index.js
Don't show error for forks when using `pull_request_target` event. Update example to mention `pull_request_target` and how to down scope as necessary.
* https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target
* https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
=> Enhance check for missing permissions on forks

README.md, action.yml, dist/index.js, src/index.js
Adds `auto_commit` to prevent commits when `auto_fix` is enabled.
This allows someone to do this:
```yaml
- name: Run linters
uses: wearerequired/lint-action@master
with:
auto_fix: true
auto_commit: false
mypy: true
mypy_args: >
--follow-imports=silent
--ignore-missing-imports
--implicit-optional
--no-strict-optional
autopep8: true
autopep8_args: >
--max-line-length 120
- name: suggester / lint
uses: reviewdog/action-suggester@v1
with:
tool_name: lint
```
which gives you the `mypy` messages from `lint-action` but with the `autopep8` changes as suggested changes via `reviewdog`.
Pretty much resolves #436 as it can be achieved through `reviewdog`.
=> Add auto_commit input

action.yml
Fixes #352.
[Stylelint 14.0.0](https://stylelint.io/migration-guide/to-14/) only supports CSS by default. Any other extension requires to install an appropriate syntax.
=> Use only CSS as default extension for stylelint

.github/workflows/test.yml, README.md
These are just some minor changes to reflect how a current setup is done with dotnet-format as the `dotnet tool install` command is no longer needed on the latest SDK's.
Also noticed that I fumbled a copy & paste on the linter support table as dotnet-format doesn't have extension options, so we got that fixed.
=> docs: dotnet-format fixes

src/linters/swiftlint.js, test/linters/projects/swiftlint/Mintfile
See https://github.com/realm/SwiftLint/blob/0.50.3/CHANGELOG.md#0490-asynchronous-defuzzer.
=> Replace deprecated autocorrect command for swiftlint auto-fixing
